CREATE DATABASE IF NOT EXISTS db_users;
USE db_users;

CREATE TABLE IF NOT EXISTS usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    idade INT NOT NULL,
    pontuacao DECIMAL(10,2) NOT NULL
);